//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuixiuVSTO.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2017sum
    {
        public string 机构 { get; set; }
        public string 姓名 { get; set; }
        public string 职工号 { get; set; }
        public string 身份证号码 { get; set; }
        public Nullable<decimal> 工资 { get; set; }
        public Nullable<decimal> 奖金 { get; set; }
        public Nullable<decimal> 奖励性补贴 { get; set; }
        public string 机构编号 { get; set; }
        public Nullable<decimal> 年合计收入 { get; set; }
    }
}
