//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuixiuVSTO.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2018pay
    {
        public string 职工号 { get; set; }
        public string 姓名 { get; set; }
        public string 科室 { get; set; }
        public string 身份证号码 { get; set; }
        public Nullable<double> 工资应发合计 { get; set; }
        public Nullable<double> 全年奖金合计 { get; set; }
        public Nullable<double> 年终奖和补加款 { get; set; }
        public Nullable<double> 全年收入合计 { get; set; }
        public Nullable<double> 去年合计收入 { get; set; }
    }
}
